version: '3.8'
services:
  skuconfig-api-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal/skuconfig
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache


  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"